DBMS:
  HOST: 100.100.100.100
  USER: root
  PASSWORD: sdqd32d2
  NAME: ai-db

ANN:
  EPOCHS: 200
  BATCH_SIZE: 512
  TEST_SIZE: 0.1
  VALIDATION_SPLIT: 0.1
  MINIMUM_ACCURACY: 0.75
  MODEL_FILE: neurolNetwork.pickle
  ONE_HOT_MODEL_FILE: predict_one_hot_encoding.pickle

OTHER:
  MODEL_PATH: aimodels/
  BACKUP_PATH: backupModels/
  FILE_NAME: files/AntennaSelectionTrainDataset.csv
  LOG_PATH: test.log

FEATURES:
  INPUT_FORMAT: ONAIR_SITE_TABLE_ID,SITE_IS_OIS,SITE_ENVIRONMENT_TYPE_ID,SITE_SITE_TYPE_ID,SITE_MONTAGE_TYPE_ID,SITE_RN_SUBREGION_ID,SITE_RN_REGION_ID,SITE_RN_MAIN_REGION_ID,SITE_COUNTY_ID,SITE_CITY_ID,SIR_CREATED_BY_USER_ID,SIR_MONTH_ID,SIR_YEAR_ID,SIR_REASON_ID,IR_TYPE_ID
  OUTPUT_FORMAT: SELECTED_ANTENNA_TYPE_ID

API:
  NAME: /api/ai/antenna/
  IS_DEBUG: True
  PORT: 21110
